"""Running projects and collecting what they measured.

Every project module exposes ``run() -> dict[str, float | int | str]``. This module
executes them, times them, records the figures they produced and writes the whole lot to
``outputs/results.json``, so the results tables in the README are generated rather than
typed by hand.
"""

from __future__ import annotations

import importlib
import json
import platform
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

from . import PROJECTS
from .paths import OUTPUT_DIR


@dataclass
class ProjectResult:
    """What one project produced: its numbers, its figures and how long it took."""

    project: str
    description: str
    seconds: float
    metrics: dict[str, Any]
    figures: list[str] = field(default_factory=list)


def run_project(name: str) -> ProjectResult:
    """Import the project module and execute its ``run()`` entry point."""
    if name not in PROJECTS:
        raise KeyError(f"unknown project '{name}'; available: {sorted(PROJECTS)}")

    module = importlib.import_module(f"classical_ml.projects.{name}")
    started = time.perf_counter()
    metrics = module.run()
    elapsed = time.perf_counter() - started

    figure_dir = OUTPUT_DIR / name
    figures = sorted(path.name for path in figure_dir.glob("*.png")) if figure_dir.exists() else []
    return ProjectResult(name, PROJECTS[name], round(elapsed, 2), metrics, figures)


def write_results(results: list[ProjectResult]) -> None:
    """Merge ``results`` into ``outputs/results.json``, keeping projects not run this time."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUTPUT_DIR / "results.json"

    payload: dict[str, Any] = {"environment": {}, "projects": {}}
    if path.exists():
        payload = json.loads(path.read_text())

    payload["environment"] = _environment()
    for result in results:
        payload["projects"][result.project] = asdict(result)

    payload["projects"] = {name: payload["projects"][name] for name in PROJECTS if name in payload["projects"]}
    path.write_text(json.dumps(payload, indent=2, default=str) + "\n")


def results_markdown(path: Path | None = None) -> str:
    """Render ``outputs/results.json`` as a Markdown record of every project run."""
    path = path or (OUTPUT_DIR / "results.json")
    payload = json.loads(Path(path).read_text())

    lines = [
        "# Results",
        "",
        "Generated by `python -m classical_ml --report` from `outputs/results.json`.",
        "Every number below comes from the project module of the same name, on a fixed seed.",
        "",
        "| Package | Version |",
        "| --- | --- |",
    ]
    lines += [f"| {name} | {version} |" for name, version in payload.get("environment", {}).items()]

    for name, entry in payload.get("projects", {}).items():
        lines += [
            "",
            f"## {name}: {entry['description']}",
            "",
            f"Runtime {entry['seconds']}s. Figures: "
            + (", ".join(f"`{figure}`" for figure in entry["figures"]) or "none"),
            "",
            "| Metric | Value |",
            "| --- | --- |",
        ]
        for key, value in entry["metrics"].items():
            rendered = f"{value:.4g}" if isinstance(value, float) else str(value)
            lines.append(f"| {key} | {rendered} |")

    return "\n".join(lines) + "\n"


def write_results_markdown() -> Path:
    """Write the Markdown record next to the JSON it is built from."""
    destination = OUTPUT_DIR / "RESULTS.md"
    destination.write_text(results_markdown())
    return destination


def _environment() -> dict[str, str]:
    import matplotlib
    import numpy
    import pandas
    import scipy
    import sklearn

    return {
        "python": platform.python_version(),
        "numpy": numpy.__version__,
        "pandas": pandas.__version__,
        "scikit-learn": sklearn.__version__,
        "scipy": scipy.__version__,
        "matplotlib": matplotlib.__version__,
    }


def format_metrics(metrics: dict[str, Any], limit: int | None = None) -> str:
    """Render a metrics dict as a compact single-line summary."""
    items = list(metrics.items())[: limit or len(metrics)]
    parts = []
    for key, value in items:
        parts.append(f"{key}={value:.4g}" if isinstance(value, float) else f"{key}={value}")
    return ", ".join(parts)
